name: Publish to Crates.io

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Source
        uses: actions/checkout@v4

      - name: Initialize Stable Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Authenticate and Publish to Crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN
